### ISSUE TITLE
`overridenote` in `\pdfpcsetup` has no effect

### ISSUE THREAD

**Issue by LRitzdorf** [pdfpc/latex-pdfpc#10]
When using the `\pdfpc` command to configure pdfpc options, the `overridenote` command (at least; there may be others that I haven't tested) has no apparent effect.

However, a combined approach does work as expected:
```latex
\documentclass{beamer}
\usepackage[overridenote]{pdfpc}
\pdfpcsetup{
    % overridenote here seems to do nothing
    duration=15,
    lastminutes=2,
    % But other keys do work
}

\begin{document}
\begin{frame}
Testing...
\note{This note may or may not show up properly in pdfpc, depending on load options.}
\end{frame}
\end{document}
```

**Comment by fnevgeny** [comment]
Unless you know how to fix it, I think this should be documented, that's all. (Similar, e.g., to `pdfusetitle` in the case of the `hyperref` package).
