### ISSUE TITLE
Diverging master branch, release and CTAN version

### ISSUE THREAD

**Issue by Trenar** [pdfpc/latex-pdfpc#14]
Hi all, 
thanks for you work on pdfpc + the latex package. I really enjoy using it. 

However, I just recognized (while searching for an overlay-aware `pdfpcnote`) that the current version of the master branch including #11 is *not* the CTAN version 0.7.0 (dated 2022/07/05). Further, on the release page of this repo, v0.6.0 is still the "most recent" version. 

That caused some confusion for me.

**Comment by AndreasBilke** [comment]
Thanks for pointing out this issue! I pushed/released a new version which should be in sync with ctan.

The remaining commits on master are currently not released and should be seen as dev currently. I will soon release a new minor version for the remaining stuff on master.

**Comment by AndreasBilke** [comment]
I relased v0.7.1. This will be soon available on ctan.
