### ISSUE TITLE
markdown: unordered nested lists

### ISSUE THREAD

**Issue by Trenar** [pdfpc/latex-pdfpc#15]
Hi all, 

what's the correct way of entering a second indentation level to an unordered list using the latex-pdfpc package?

I want to have something like this: 
------------
- Item 1, level 1
  - Item 1, level 2
  - Item 2, level 2
- Item 2, level 1
------------

However, the code 
`\pdfpcnote{This should resemble a multi-level unordered list.\\ \\- Item 1, level 1\\    - Item 1, level 2\\    - Item 2, level2\\- Item 2, level 1}`

results in the following: 
![image](https://github.com/pdfpc/latex-pdfpc/assets/31891152/4afe65cb-73fc-4f8b-a88d-daa83f9b7993)

As you can see, everything is in the first indentation level. That's also independent of the number of whitespace (2 or 4) before the second-level items.

-------------------------------
---------------------------------
## EDIT
I just found that using `\ ` instead of the whitespace resolves that issue. So, for creating the above nested list, the correct tex line would be `\pdfpcnote{This should resemble a multi-level unordered list.\\ \\- Item 1, level 1\\\ \ - Item 1, level 2\\\ \ - Item 2, level2\\- Item 2, level 1}`

Still I think this is somewhat of a bug, or should be documented

**Comment by fnevgeny** [comment]
Indeed. BTW, you can use line breaks inside of `\pdfpcnote{}`
