### ISSUE TITLE
Docs: `hidenotes` must be a package option.

### ISSUE THREAD

**Issue by Turakar** [pdfpc/latex-pdfpc#16]
Thank you for this convenient extension!

The documentation PDF contains the following statement:

> When sharing slides, one may want to omit the (potentially private)
> notes, by using the hidenotes option. Enabling it will disable notes, in-
> cluding Beamer notes if overridenote was specified.

This suggests that notes would be inaccessible to a third-party user if `hidenotes` is specified. This is not the case (the third-party user may just use pdfpc or another capable PDF viewer like Okular). I therefore suggest to remove the statement in parentheses and maybe even add a warning. It might further be worth considering to add an option which actually excludes the notes from the PDF.

**Comment by fnevgeny** [comment]
> This suggests that notes would be inaccessible to a third-party user if `hidenotes` is specified.

Right, that's how it's supposed to work. What makes you think it doesn't?

**Comment by Turakar** [comment]
The text suggests that the notes can be kept private, but this is not the case.

**Comment by fnevgeny** [comment]
Again, it works for me, and I don't understand why it wouldn't for you. You need to provide an MWE proving your point.

**Comment by Turakar** [comment]
https://www.overleaf.com/read/hxyyngbdwhrj#3b539c

In this example, you can see that the default Overleaf PDF viewer shows the note, and while Okular hides it correctly you can find it using "Annotations" in the sidebar. As such, the note is not kept private (i.e. inaccessible to a third-party user).

![grafik](https://github.com/pdfpc/latex-pdfpc/assets/3958680/8bf0c231-029c-46c6-bbfd-e11a46e0025f)

**Comment by fnevgeny** [comment]
Use it as an option when loading the package, it doesn't work via `\pdfpcsetup`.  It just needs to be mentioned in the docs (similar to `overridenote`).

**Comment by Turakar** [comment]
Ok, the note seems to be completely absent from the PDF, now :slightly_smiling_face: It would have been useful to create a warning in the other case - but I am unfamiliar with programming TeX packages, so I do not know how hard this is.
