### ISSUE TITLE
guidance about removing notes from existing PDF files

### ISSUE THREAD

**Issue by muelli** [pdfpc/latex-pdfpc#3]
I want to publish my slides, but remove my pdfpcnotes (and information such as the enduserslide). I don't necessarily want to compile again, because running the compiler is relatively expensive. Also, it should be relatively easy to filter our all the annotations from PDF.
I would appreciate if the documentation mentioned how to strip annotations with external tools but I understand if this is considered to be out of scope.

From what I have gathered, the best way currently is to run a series of commands: https://gist.github.com/stefanschmidt/5248592 but that also looks like it'll break some PDFs, at least.
pdfcpu https://pdfcpu.io/ can remove annotations :) But it seems to not remove the enduserslide.

**Comment by fnevgeny** [comment]
IMO, this functionality is certainly not what a LaTeX package can or should do... It's rather straightforward to code such a utility using poppler in any binding one likes. For me, running pdflatex is easier.

**Comment by muelli** [comment]
how do you do it, then?

**Comment by fnevgeny** [comment]
Just use the `hidenotes` option.
