### ISSUE TITLE
Make `\pdfpcnote` overlay-specification aware

### ISSUE THREAD

**Issue by LRitzdorf** [pdfpc/latex-pdfpc#9]
Currently, the provided `\pdfpcnote` (and, when `overridenote` is set, `\note`) commands are not compatible with Beamer's overlay specifications. Beamer documentation explicitly recommends using overlays with their built-in `\note` command, so similar support in the pdfpc package would be greatly appreciated.

Additionally, implementing this support should be extremely straightforward — probably requiring just one extra `\only` in the relevant command definitions. I've experimented *very slightly* with such redefinitions myself, and given the apparent ease of implementation, would be willing to PR this feature if desired.

(Section 9.2 of the Beamer manual should be relevant, if additional detail is needed.)

**Comment by fnevgeny** [comment]
> I've experimented _very slightly_ with such redefinitions myself, and given the apparent ease of implementation, would be willing to PR this feature if desired.

Sure, please go ahead!
